name: 🚀 Deploy to VPS (btreeadminportal)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create .ssh Directory
        run: mkdir -p ~/.ssh

      - name: Add Server to Known Hosts
        run: ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd /var/www/btreeadminportal
            sudo chown -R deployer:www-data /var/www/btreeadminportal
            sudo chmod -R 755 /var/www/btreeadminportal
            git reset --hard HEAD
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --no-input --clear
            sudo systemctl restart btreeadminportal
            sudo systemctl restart nginx
